config/routes.rb
# == Route Map (Updated 2014-05-16 14:01)
#
#                   Prefix Verb   URI Pattern                            Controller#Action
#       search_suggestions GET    /search_suggestions(.:format)          search_suggestions#index
#                          POST   /search_suggestions(.:format)          search_suggestions#create
#    new_search_suggestion GET    /search_suggestions/new(.:format)      search_suggestions#new
#   edit_search_suggestion GET    /search_suggestions/:id/edit(.:format) search_suggestions#edit
#        search_suggestion GET    /search_suggestions/:id(.:format)      search_suggestions#show
#                          PATCH  /search_suggestions/:id(.:format)      search_suggestions#update
#                          PUT    /search_suggestions/:id(.:format)      search_suggestions#update
#                          DELETE /search_suggestions/:id(.:format)      search_suggestions#destroy
#                  contact GET    /contact(.:format)                     pages#contact
#           privacy_policy GET    /privacy_policy(.:format)              pages#privacy_policy
#         terms_of_service GET    /terms_of_service(.:format)            pages#terms_of_service
#                    about GET    /about(.:format)                       pages#about
#              user_groups GET    /user_groups(.:format)                 user_groups#index
#                          POST   /user_groups(.:format)                 user_groups#create
#           new_user_group GET    /user_groups/new(.:format)             user_groups#new
#          edit_user_group GET    /user_groups/:id/edit(.:format)        user_groups#edit
#               user_group GET    /user_groups/:id(.:format)             user_groups#show
#                          PATCH  /user_groups/:id(.:format)             user_groups#update
#                          PUT    /user_groups/:id(.:format)             user_groups#update
#                          DELETE /user_groups/:id(.:format)             user_groups#destroy
#         new_user_session GET    /users/sign_in(.:format)               devise/sessions#new
#             user_session POST   /users/sign_in(.:format)               devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)              devise/sessions#destroy
#            user_password POST   /users/password(.:format)              devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)          devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)         devise/passwords#edit
#                          PATCH  /users/password(.:format)              devise/passwords#update
#                          PUT    /users/password(.:format)              devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                registrations#cancel
#        user_registration POST   /users(.:format)                       registrations#create
#    new_user_registration GET    /users/sign_up(.:format)               registrations#new
#   edit_user_registration GET    /users/edit(.:format)                  registrations#edit
#                          PATCH  /users(.:format)                       registrations#update
#                          PUT    /users(.:format)                       registrations#update
#                          DELETE /users(.:format)                       registrations#destroy
#             user_profile POST   /users/:user_id/profile(.:format)      profiles#create
#         new_user_profile GET    /users/:user_id/profile/new(.:format)  profiles#new
#        edit_user_profile GET    /users/:user_id/profile/edit(.:format) profiles#edit
#                          GET    /users/:user_id/profile(.:format)      profiles#show
#                          PATCH  /users/:user_id/profile(.:format)      profiles#update
#                          PUT    /users/:user_id/profile(.:format)      profiles#update
#                          DELETE /users/:user_id/profile(.:format)      profiles#destroy
#                    users GET    /users(.:format)                       users#index
#                          POST   /users(.:format)                       users#create
#                 new_user GET    /users/new(.:format)                   users#new
#                edit_user GET    /users/:id/edit(.:format)              users#edit
#                     user GET    /users/:id(.:format)                   users#show
#                          PATCH  /users/:id(.:format)                   users#update
#                          PUT    /users/:id(.:format)                   users#update
#                          DELETE /users/:id(.:format)                   users#destroy
#                     root GET    /                                      welcome#index
#

Rails.application.routes.draw do
  resources :search_suggestions

  get '/contact' => 'pages#contact'
  get '/privacy_policy' => 'pages#privacy_policy'
  get '/terms_of_service' => 'pages#terms_of_service'
  get '/about' => 'pages#about'

  resources :user_groups

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users do
    resource :profile
  end

  root 'welcome#index'
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  #has_many :affiliations
  #has_many :users, through: :affiliations

  has_many :venues, inverse_of: :user_group
  has_many :locations, through: :venues

  validates :name, presence: true
  validates :homepage, presence: true

  accepts_nested_attributes_for :venues
end

# == Schema Information
# Schema version: 20140516063750
#
# Table name: user_groups
#
#  id          :integer          not null, primary key
#  name        :string(255)      indexed
#  description :text
#  homepage    :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#
# Indexes
#
#  index_user_groups_on_name  (name) UNIQUE
#

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :set_user_group, only: [:show, :edit, :update, :destroy]

  def index
    @user_groups = UserGroup.all
  end

  def show
  end

  def new
    @user_group = UserGroup.new
    @user_group.venues.build.build_location


    ap @user_group
    @user_group
  end

  def edit
  end

  def create
    @user_group = UserGroup.new(user_group_params)



    respond_to do |format|
      if @user_group.save
        format.html { redirect_to @user_group, notice: 'User group was successfully created.' }
        format.json { render :show, status: :created, location: @user_group }
      else
        format.html { render :new }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user_group.update(user_group_params)
        format.html { redirect_to @user_group, notice: 'User group was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_group }
      else
        format.html { render :edit }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user_group.destroy
    respond_to do |format|
      format.html { redirect_to user_groups_url, notice: 'User group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_group
    @user_group = UserGroup.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_group_params
    params.require(:user_group).permit(:name, :description, :homepage, venues_attributes: [locations: [:name, :full_street_address, :latitude, :longitude]])
  end
end

app/views/user_groups/edit.html.erb
<h1>Editing user_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_group %> |
<%= link_to 'Back', user_groups_path %>

app/views/user_groups/index.html.erb
<% if @user_groups.empty? %>

  <strong>No User-Groups to show.</strong>

<% else %>
  <% @user_groups.each do |ug| %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
    <div class="container">
      <div class="row">
        <div class="col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
          <div class="well profile">
            <div class="col-sm-12">
              <div class="col-xs-12 col-sm-8">
                <h2><%= ug.name %></h2>
                <% unless ug.description.blank? %>
                  <p><strong>Description: </strong> <%= ug.description %> </p>
                <% end %>
                <!--
                <p><strong>Hobbies: </strong> Read, out with friends, listen to music, draw and learn new things. </p>
                <p><strong>Skills: </strong>
                  <span class="tags">html5</span>
                  <span class="tags">css3</span>
                  <span class="tags">jquery</span>
                  <span class="tags">bootstrap3</span>
                </p>
                -->
              </div>
              <div class="col-xs-12 col-sm-4 text-center">
                <figure>
                  <!-- 200px x 200px -->
                  <img src="http://www.localcrimenews.com/wp-content/uploads/2013/07/default-user-icon-profile.png" alt="" class="img-circle img-responsive">
                  <figcaption class="ratings">
                    <!--
                    <p>Ratings
                      <a href="#">
                        <span class="fa fa-star"></span>
                      </a>
                      <a href="#">
                        <span class="fa fa-star"></span>
                      </a>
                      <a href="#">
                        <span class="fa fa-star"></span>
                      </a>
                      <a href="#">
                        <span class="fa fa-star"></span>
                      </a>
                      <a href="#">
                        <span class="fa fa-star-o"></span>
                      </a>
                    </p>
                    -->
                  </figcaption>
                </figure>
              </div>
            </div>
            <div class="col-xs-12 divider text-center">

              <div class="col-xs-12 col-sm-4 emphasis">
                <h2><strong> <%= ug.affiliations.count %> </strong></h2>
                <p><small>Members</small></p>
                <button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span> Join </button>
              </div>

              <!--
              <div class="col-xs-12 col-sm-4 emphasis">
                <h2><strong>245</strong></h2>
                <p><small>Members</small></p>
                <button class="btn btn-info btn-block"><span class="fa fa-user"></span> View Profile </button>
              </div>
              -->
              <!--
              <div class="col-xs-12 col-sm-4 emphasis">
                <h2><strong>43</strong></h2>
                <p><small>Snippets</small></p>
                <div class="btn-group dropup btn-block">
                  <button type="button" class="btn btn-primary"><span class="fa fa-gear"></span> Options </button>
                  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                    <span class="sr-only">Toggle Dropdown</span>
                  </button>
                  <ul class="dropdown-menu text-left" role="menu">
                    <li><a href="#"><span class="fa fa-envelope pull-right"></span> Send an email </a></li>
                    <li><a href="#"><span class="fa fa-list pull-right"></span> Add or remove from a list  </a></li>
                    <li class="divider"></li>
                    <li><a href="#"><span class="fa fa-warning pull-right"></span>Report this user for spam</a></li>
                    <li class="divider"></li>
                    <li><a href="#" class="btn disabled" role="button"> Unfollow </a></li>
                  </ul>
                </div>
                -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
<br>
<%= link_to 'New User group', new_user_group_path %>

app/views/user_groups/new.html.erb
<h1>Register Your User-Group</h1>

<input type="hidden" id="formatted_address">
<%= simple_form_for(@user_group) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :name, required: true, placeholder: 'Homebrew Computer Club' %>
    <%= f.input :description, placeholder: 'Are you building your own computer? Terminal? T V Typewriter? I/O device? or some other digital black-magic box?  Or are you buying time on a time-sharing service?  If so, you might like to come to a gathering of people with like-minded interests. Exchange information, swap ideas, talk shop, help work on a project, whatever . . .' %>
    <%= f.input :homepage, required: true, placeholder: 'http://www.your-user-group.org', hint: 'Where can we go for more information? Could be a Meetup page or even a Twitter account.' %>
    <fieldset class="container">
      <legend>Location</legend>
      <div class="row">
        <div class="col-xs-5">
          <%= f.simple_fields_for :venues do |venues_f| %>
            <%= venues_f.simple_fields_for :locations do |locations_f| %>
              <%= locations_f.input :name, required: true, placeholder: 'French Gordan\'s Garage', hint: 'What is the name of the place you typically meet at? Could be the name of a company, restaurant, or co-working space. (You can add more later.)' %>
              <%= locations_f.input :full_street_address, required: true, placeholder: '614 18th Ave., Menlo Park (near Marsh Road)', hint: "As much of the address as you know. Please provide at least the city, state/region/provice, and country.", as: :text %>
              <%= locations_f.input :latitude, as: :hidden %>
              <%= locations_f.input :longitude, as: :hidden %>
            <% end %>
          <% end %>
        </div>

        <div class="col-xs-5">
          <div id="map"></div>
        </div>

      </div>
    </fieldset>
  </div>
  <div class="form-actions">
    <%= f.button :submit, 'Save' %>
  </div>
<% end %>

<div id="confirm-address" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="updateAddressModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="updateAddressModalLabel">Did we understand your address correctly?</h4>
      </div>

      <div class="modal-body">
        <div class="container">
          <div class="row">

            <div class="col-xs-3">
              <div class="well" style="height: 150px;">
                <h4>You entered:</h4>
                <address id="original-address"></address>
              </div>
            </div>

            <div class="col-xs-3">
              <div class="well" style="height: 150px;">
                <h4>But we found:</h4>
                <address id="formatted-address"></address>
              </div>
            </div>

          </div>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" id="use-original-address">Use original</button>
        <button type="button" class="btn btn-primary" id="use-formatted-address">Replace with updated address</button>
      </div>

    </div>
  </div>
</div>

app/views/user_groups/show.html.erb
<div class="container">
  <div class="row well">
    <div class="col-md-2">
      <ul class="nav nav-pills nav-stacked well">
        <li  class="active"><a href="#"><i class="fa fa-envelope"></i> Compose</a></li>
        <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
        <li><a href="#"><i class="fa fa-user"></i> Profile</a></li>
        <li><a href="#"><i class="fa fa-key"></i> Security</a></li>
        <li><a href="#"><i class="fa fa-sign-out"></i> Logout</a></li>
      </ul>
    </div>
    <div class="col-md-10">
      <div class="panel">
        <img class="pic img-circle" src="http://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/twDq00QDud4/s120-c/photo.jpg" alt="...">
        <div class="name"><small><%= @user_group.name %></small></div>
        <a href="#" class="btn btn-xs btn-primary pull-right" style="margin:10px;"><span class="glyphicon glyphicon-picture"></span> Change cover</a>
      </div>

      <br><br><br>
      <ul class="nav nav-tabs" id="myTab">
        <li class="active"><a href="#inbox" data-toggle="tab"><i class="fa fa-envelope-o"></i> Inbox</a></li>
        <li><a href="#sent" data-toggle="tab"><i class="fa fa-reply-all"></i> Sent</a></li>
        <li><a href="#assignment" data-toggle="tab"><i class="fa fa-file-text-o"></i> Assignment</a></li>
        <li><a href="#event" data-toggle="tab"><i class="fa fa-clock-o"></i> Event</a></li>
      </ul>

      <div class="tab-content">

        <div class="tab-pane active" id="inbox">
          <% @user_group.affiliations.each do |affiliation| %>
            <a type="button" data-toggle="collapse" data-target="#a1">
              <div class="btn-toolbar well well-sm" role="toolbar"  style="margin:0px;">
                <div class="btn-group"><input type="checkbox"></div>
                <div class="btn-group col-md-3"><%= affiliation.role %></div>
                <div class="btn-group col-md-8">
                  <b><%= affiliation.user.email %></b>
                  <div class="pull-right"><i class="glyphicon glyphicon-time"></i>
                    12:10 PM
                    <button class="btn btn-primary btn-xs" data-toggle="modal" data-target=".bs-example-modal-lg"><i class="fa fa-share-square-o"> Reply</i></button></div>
                </div>
              </div>
            </a>
          <% end %>
          <div id="a1" class="collapse out well">This is the message body1</div>
          <br>
          <button class="btn btn-primary btn-xs"><i class="fa fa-check-square-o"></i> Delete Checked Item's</button>
        </div>


        <div class="tab-pane" id="sent">
          <a type="button" data-toggle="collapse" data-target="#s1">
            <div class="btn-toolbar well well-sm" role="toolbar"  style="margin:0px;">
              <div class="btn-group"><input type="checkbox"></div>
              <div class="btn-group col-md-3">Kumar</div>
              <div class="btn-group col-md-8"><b>This is reply from Bootstrap plugin</b> <div class="pull-right"><i class="glyphicon glyphicon-time"></i> 12:30 AM</div> </div>
            </div>
          </a>
          <div id="s1" class="collapse out well">This is the message body1</div>
          <br>
          <button class="btn btn-primary btn-xs"><i class="fa fa-check-square-o"></i> Delete Checked Item's</button>
        </div>


        <div class="tab-pane" id="assignment">
          <a href=""><div class="well well-sm" style="margin:0px;">Open GL Assignments <span class="pull-right"><i class="glyphicon glyphicon-time"></i> 12:20 AM 20 Dec 2014 </span></div></a>
        </div>

        <div class="tab-pane" id="event">
          <div class="media">
            <a class="pull-left" href="#">
              <img class="media-object img-thumbnail" width="100" src="http://cfi-sinergia.epfl.ch/files/content/sites/cfi-sinergia/files/WORKSHOPS/Workshop1.jpg" alt="...">
            </a>
            <div class="media-body">
              <h3 class="media-heading">Animation Workshop</h3>
              2Days animation workshop to be conducted
            </div>
          </div>
        </div>



      </div>

    </div>
  </div>


</div>




<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content"><br/><br/>
      <form class="form-horizontal">
        <fieldset>
          <!-- Text input-->
          <div class="form-group">
            <label class="col-md-2 control-label" for="body">Body :</label>
            <div class="col-md-8">
              <input id="body" name="body" type="text" placeholder="Message Body" class="form-control input-md">

            </div>
          </div>

          <!-- Textarea -->
          <div class="form-group">
            <label class="col-md-2 control-label" for="message">Message :</label>
            <div class="col-md-8">
              <textarea class="form-control" id="message" name="message"></textarea>
            </div>
          </div>

          <!-- Button -->
          <div class="form-group">
            <label class="col-md-2 control-label" for="send"></label>
            <div class="col-md-8">
              <button id="send" name="send" class="btn btn-primary">Send</button>
            </div>
          </div>

        </fieldset>
      </form>

    </div>
  </div>
</div>

<%= link_to 'Edit', edit_user_group_path(@user_group) %> |
<%= link_to 'Back', user_groups_path %>