config/routes.rb
# == Route Map (Updated 2014-05-16 14:01)
#
#                   Prefix Verb   URI Pattern                            Controller#Action
#       search_suggestions GET    /search_suggestions(.:format)          search_suggestions#index
#                          POST   /search_suggestions(.:format)          search_suggestions#create
#    new_search_suggestion GET    /search_suggestions/new(.:format)      search_suggestions#new
#   edit_search_suggestion GET    /search_suggestions/:id/edit(.:format) search_suggestions#edit
#        search_suggestion GET    /search_suggestions/:id(.:format)      search_suggestions#show
#                          PATCH  /search_suggestions/:id(.:format)      search_suggestions#update
#                          PUT    /search_suggestions/:id(.:format)      search_suggestions#update
#                          DELETE /search_suggestions/:id(.:format)      search_suggestions#destroy
#                  contact GET    /contact(.:format)                     pages#contact
#           privacy_policy GET    /privacy_policy(.:format)              pages#privacy_policy
#         terms_of_service GET    /terms_of_service(.:format)            pages#terms_of_service
#                    about GET    /about(.:format)                       pages#about
#              user_groups GET    /user_groups(.:format)                 user_groups#index
#                          POST   /user_groups(.:format)                 user_groups#create
#           new_user_group GET    /user_groups/new(.:format)             user_groups#new
#          edit_user_group GET    /user_groups/:id/edit(.:format)        user_groups#edit
#               user_group GET    /user_groups/:id(.:format)             user_groups#show
#                          PATCH  /user_groups/:id(.:format)             user_groups#update
#                          PUT    /user_groups/:id(.:format)             user_groups#update
#                          DELETE /user_groups/:id(.:format)             user_groups#destroy
#         new_user_session GET    /users/sign_in(.:format)               devise/sessions#new
#             user_session POST   /users/sign_in(.:format)               devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)              devise/sessions#destroy
#            user_password POST   /users/password(.:format)              devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)          devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)         devise/passwords#edit
#                          PATCH  /users/password(.:format)              devise/passwords#update
#                          PUT    /users/password(.:format)              devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                registrations#cancel
#        user_registration POST   /users(.:format)                       registrations#create
#    new_user_registration GET    /users/sign_up(.:format)               registrations#new
#   edit_user_registration GET    /users/edit(.:format)                  registrations#edit
#                          PATCH  /users(.:format)                       registrations#update
#                          PUT    /users(.:format)                       registrations#update
#                          DELETE /users(.:format)                       registrations#destroy
#             user_profile POST   /users/:user_id/profile(.:format)      profiles#create
#         new_user_profile GET    /users/:user_id/profile/new(.:format)  profiles#new
#        edit_user_profile GET    /users/:user_id/profile/edit(.:format) profiles#edit
#                          GET    /users/:user_id/profile(.:format)      profiles#show
#                          PATCH  /users/:user_id/profile(.:format)      profiles#update
#                          PUT    /users/:user_id/profile(.:format)      profiles#update
#                          DELETE /users/:user_id/profile(.:format)      profiles#destroy
#                    users GET    /users(.:format)                       users#index
#                          POST   /users(.:format)                       users#create
#                 new_user GET    /users/new(.:format)                   users#new
#                edit_user GET    /users/:id/edit(.:format)              users#edit
#                     user GET    /users/:id(.:format)                   users#show
#                          PATCH  /users/:id(.:format)                   users#update
#                          PUT    /users/:id(.:format)                   users#update
#                          DELETE /users/:id(.:format)                   users#destroy
#                     root GET    /                                      welcome#index
#

Rails.application.routes.draw do
  resources :search_suggestions

  get '/contact' => 'pages#contact'
  get '/privacy_policy' => 'pages#privacy_policy'
  get '/terms_of_service' => 'pages#terms_of_service'
  get '/about' => 'pages#about'

  resources :user_groups

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users do
    resource :profile
  end

  root 'welcome#index'
end

app/views/layouts/_flash_messages.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "User-Group List: Build. Participate. Support." %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : '' %>">
    <meta name="author" content="<%= content_for?(:author) ? yield(:author) : '' %>">
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">

    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'User-Group List', user_groups_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <%= nav_tab('Home', root_path) %>
            <%= nav_tab('User-Groups List', user_groups_path) %>
            <% if current_user %>
              <%= nav_tab('Me', user_profile_path(current_user)) %>
            <% end %>
            <%#= nav_tab('About', about_path) %>
            <%#= nav_tab('Contact', contact_path) %>
            <!--
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
            -->
          </ul>
          <!-- <div class="col-sm-3 col-md-3">
            <form class="navbar-form" role="search">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search User-Groups" name="q" id="q">
                <div class="input-group-btn">
                  <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
              </div>
            </form>
          </div> -->
        </div>
        <!--/.nav-collapse -->
      </div>
    </div>


    <div class="container">
      <div class="row">
        <%= render 'layouts/flash_messages' %>
        <% if current_user %><%= link_to 'sign out', destroy_user_session_path, method: :delete %><% end %>
      </div>

      <%= yield %>
    </div>
  </body>
</html>